version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/ikeogu/AIIRPUB/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  iiarpub-job:
    environment:
      DB_DATABASE: ishledpg_stage_api
      DB_USERNAME: ishledpg_stage_api
      DB_PASSWORD: P@$$w0rd@123
      DB_PORT: 3306
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          version: 2.1
          
          jobs:
            build:
              docker:
                - image: cimg/base:stable
                  
              working_directory: ~/repo
              steps:
                - checkout
                - run: cp .env.testing .env
                - run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
                - run: php artisan key:generate
                - run: php artisan config:clear
                - run: php artisan migrate --seed
                - run:
                    name: PHPStan
                    command: ./vendor/bin/phpstan analyze --memory-limit=-1 --no-progress
                - run:
                    name: Code Analysis
                    command: ./vendor/bin/phpstan analyse
                - run:
                    name: PHPUnit
                    command: ./vendor/bin/pest --parallel --coverage --min=80
          

workflows:
  my-custom-workflow:
    jobs:
      - iiarpub-job