name: PHP Composer

on:
  push:
    branches: ["main", "develop"]

permissions:
  contents: read

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    env:
      COMPOSER_VERSION: 2
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Install exif extension
        run: sudo apt-get install php-exif

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer_config
        uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: get_config

      - name: Cache composer downloads
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer_config.outputs.composer_cache_dir }}
          key: composer-v${{ steps.composer_config.outputs.composer_major_version }}

      - name: Run composer install
        uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: install --ignore-platform-req=ext-exif
        
      - name: Run phpstan
        run: vendor/bin/phpstan analyze -c phpstan.neon --no-progress --no-interaction

      - name: Run pest
        run: vendor/bin/pest

  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    env:
      COMPOSER_VERSION: 2
      DB_HOST: ${{ secrets.db_host }}
      DB_DATABASE: ${{ secrets.db_name }}
      DB_USERNAME: ${{ secrets.db_username }}
      DB_PASSWORD: ${{ secrets.db_password }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer_config
        uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: get_config

      - name: Cache composer downloads
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer_config.outputs.composer_cache_dir }}
          key: composer-v${{ steps.composer_config.outputs.composer_major_version }}

      - name: Run composer install
        uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: install --ignore-platform-req=ext-exif
          
      - name: Run database migrations
        run: php artisan migrate --force
        
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          port: ${{ secrets.ftp_port }}
          password: ${{ secrets.ftp_password }}
